/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "github.com/baum/noobaa-source/pkg/apis/noobaasources/v1alpha1"
)

// FakeNooBaaSources implements NooBaaSourceInterface
type FakeNooBaaSources struct {
	Fake *FakeNooBaasV1alpha1
	ns   string
}

var noobaasourcesResource = schema.GroupVersionResource{Group: "noobaa.knative.dev", Version: "v1alpha1", Resource: "noobaasources"}

var noobaasourcesKind = schema.GroupVersionKind{Group: "noobaa.knative.dev", Version: "v1alpha1", Kind: "NooBaaSource"}

// Get takes name of the noobaasource, and returns the corresponding noobaasource object, and an error if there is any.
func (c *FakeNooBaaSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NooBaaSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(noobaasourcesResource, c.ns, name), &v1alpha1.NooBaaSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaSource), err
}

// List takes label and field selectors, and returns the list of NooBaaSources that match those selectors.
func (c *FakeNooBaaSources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NooBaaSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(noobaasourcesResource, noobaasourcesKind, c.ns, opts), &v1alpha1.NooBaaSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NooBaaSourceList{ListMeta: obj.(*v1alpha1.NooBaaSourceList).ListMeta}
	for _, item := range obj.(*v1alpha1.NooBaaSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested noobaasources.
func (c *FakeNooBaaSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(noobaasourcesResource, c.ns, opts))

}

// Create takes the representation of a noobaasource and creates it.  Returns the server's representation of the noobaasource, and an error, if there is any.
func (c *FakeNooBaaSources) Create(ctx context.Context, noobaasource *v1alpha1.NooBaaSource, opts v1.CreateOptions) (result *v1alpha1.NooBaaSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(noobaasourcesResource, c.ns, noobaasource), &v1alpha1.NooBaaSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaSource), err
}

// Update takes the representation of a noobaasource and updates it. Returns the server's representation of the noobaasource, and an error, if there is any.
func (c *FakeNooBaaSources) Update(ctx context.Context, noobaasource *v1alpha1.NooBaaSource, opts v1.UpdateOptions) (result *v1alpha1.NooBaaSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(noobaasourcesResource, c.ns, noobaasource), &v1alpha1.NooBaaSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNooBaaSources) UpdateStatus(ctx context.Context, noobaasource *v1alpha1.NooBaaSource, opts v1.UpdateOptions) (*v1alpha1.NooBaaSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(noobaasourcesResource, "status", c.ns, noobaasource), &v1alpha1.NooBaaSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaSource), err
}

// Delete takes name of the noobaasource and deletes it. Returns an error if one occurs.
func (c *FakeNooBaaSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(noobaasourcesResource, c.ns, name), &v1alpha1.NooBaaSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNooBaaSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(noobaasourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NooBaaSourceList{})
	return err
}

// Patch applies the patch and returns the patched noobaasource.
func (c *FakeNooBaaSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NooBaaSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(noobaasourcesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NooBaaSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NooBaaSource), err
}
